name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        fleet: [will_philson/browsercontrol-aarch64, will_philson/browsercontrol-amd64, will_philson/browsercontrol-armv7hf]

    steps:
      - uses: actions/checkout@v3
      - uses: balena-io/deploy-to-balena-action@v0.9.0
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          environment: balena-cloud.com
          fleet: ${{ matrix.fleet }}
          versionbot: false
